#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1636418844                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    : https://www.alexsereno.dev
                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Take your workouts super saiyan!

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Alex Sereno                                
your_link                                 : https://www.alexsereno.dev               
your_city                                 : Austin, TX                                
email_address                             : me@alexsereno.dev
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : 
github_username                           : 
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Magical set and weight progression 
    description                           : No math required! Automatically calculates sets and reps for your next workout!
    fontawesome_icon_name                 : magic
    
  - title                                 : Extremely smart UI
    description                           : Less time clicking dozens of little buttons during a workout
    fontawesome_icon_name                 : mobile

  - title                                 : Automatic rest timers!
    description                           : Rest optimally, and reach each set with intensity
    fontawesome_icon_name                 : timer

  - title                                 : Unlimited workout backups
    description                           : All your workouts are synced to iCloud!
    fontawesome_icon_name                 : sync

  - title                                 : Automatic light / dark themes
    description                           : Late night workouts that are as easy on the eyes as you are ;)
    fontawesome_icon_name                 : adjust
  
  - title                                 : Amazing features being added all the time
    description                           : Rapid updates! Want a new feature? Request it!
    fontawesome_icon_name                 : star

  - title                                 : Charts!
    description                           : Watch your progress throughout the year and feel a sense of pride an accomplishment
    fontawesome_icon_name                 : chart

  - title                                 : Easily share your workouts and progress!
    description                           : Gym buddy want to cop your workout? Need to send your coach a chart of your gains? Share with just a click!
    fontawesome_icon_name                 : link

  - title                                 : No need to pay rent!
    description                           : You can choose to buy the product outright, if subscriptions aren't your thing! Lower than the cost of a new notebook ;)
    fontawesome_icon_name                 : info-circle

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
